name: Build and Test

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Modify to match your testing command and script

